CREATE TABLE IF NOT EXISTS public.hits
(
    hit_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    app character varying(255),
    ip character varying(45),
    "timestamp" timestamp without time zone,
    uri character varying(255),
    CONSTRAINT hits_pkey PRIMARY KEY (hit_id)
);